### ISSUE TITLE
大佬，代码clone下来后按照您的说明操作报错了呀

### ISSUE THREAD

**Issue by 1229984599** [Starry-OvO/rotate-captcha-crack#1]
我丢了一些图片在train里面，数据集结构是这个样子的
![image](https://user-images.githubusercontent.com/34052312/175286060-bd47e883-f0cd-454c-a0cf-4910679a95c4.png)
但是运行train就直接报错了
![image](https://user-images.githubusercontent.com/34052312/175285914-8deb8ca2-97fa-4894-bace-4364cab0853e.png)

**Comment by Starry-OvO** [comment]
话说你本科有参加过无线电爱好者协会吗？你这个id和我一个学姐的名字拼音一模一样

**Comment by Starry-OvO** [comment]
> 

确实是数据集太小的问题，验证用的val_dataloader的batch_size默认为48。如果你的数据集总大小只有200的话就意味着验证集只有10张图，不够填满一个batch。建议换个1000张图的数据集或者为val_dataloader指定一个比较小的batch_size
