### ISSUE TITLE
RCCNet_v0_3 的val loss一直降不下俩,但是tran loss已经很低了...

### ISSUE THREAD

**Issue by xiangbei1997** [Starry-OvO/rotate-captcha-crack#11]

**Comment by Starry-OvO** [comment]
我这里没问题啊
![eval_loss](https://user-images.githubusercontent.com/48282276/222867958-b3b875aa-a99c-4f86-8c64-d0feafff0ce4.png)
![train_loss](https://user-images.githubusercontent.com/48282276/222867961-6560862c-e550-498b-972c-2dd7f8f5dedc.png)

**Comment by xiangbei1997** [comment]
![image](https://user-images.githubusercontent.com/35731898/222869449-1efbb5bb-edea-4685-867e-d747220a707b.png)
![image](https://user-images.githubusercontent.com/35731898/222869469-3c7b3385-b090-4302-aa69-16a3b7304407.png)
这是训练的loss 和 数据集图片

**Comment by Starry-OvO** [comment]
白边得去掉，我现在数据集是仿的RotNet，也就是无白边

把`import ImgSeqFromPaths`删掉

换成自定义的

```python
from pathlib import Path
from typing import Sequence

from PIL import Image
from torch import Tensor

from rotate_captcha_crack.dataset import TypeImgSeq
from rotate_captcha_crack.utils import strip_circle_border


class ImgSeqFromPaths(TypeImgSeq):
    __slots__ = ['img_paths']

    def __init__(self, img_paths: Sequence[Path]) -> None:
        self.img_paths = img_paths

    def __len__(self) -> int:
        return self.img_paths.__len__()

    def __getitem__(self, idx: int) -> Tensor:
        img_path = self.img_paths[idx]
        img = Image.open(img_path)
        img_ts = strip_circle_border(img)
        return img_ts
```

**Comment by xiangbei1997** [comment]
> 

我在试试,谢谢大哥,合适留个码,喝一杯咖啡吗

**Comment by xiangbei1997** [comment]
剪裁的图我看了,没问题......但是还是val_loss还是无法降下来

**Comment by Starry-OvO** [comment]
v50就不必了，我还巴不得多张卡一起找问题
你数据集有多大？

**Comment by xiangbei1997** [comment]
> 

250多张,我复制了10份2500张,因为对于特定的项目

**Comment by xiangbei1997** [comment]
> v50就不必了，我还巴不得多张卡一起找问题 你数据集有多大？

佬可以留个联系方式我把数据集给你

**Comment by Starry-OvO** [comment]
你这数据集是抓出来的吗？如果是抓出来的就很有意义了，可以做个benchmark，毕竟现在评价手段匮乏

**Comment by Starry-OvO** [comment]
qq596693091

**Comment by xiangbei1997** [comment]
> 你这数据集是抓出来的吗？如果是抓出来的就很有意义了，可以做个benchmark，毕竟现在评价手段匮乏

是抓出来的
