### ISSUE TITLE
请教下Macos怎么允许此项目？

### ISSUE THREAD

**Issue by WdBly** [Starry-OvO/rotate-captcha-crack#19]
直接拉项目 运行会提示：
<img width="2559" alt="image" src="https://github.com/Starry-OvO/rotate-captcha-crack/assets/28389170/fea5d35b-54a1-4d21-99b5-dd69082482b1">

**Comment by Starry-OvO** [comment]
这个意思就是你需要一个支持CUDA计算库的设备，如果我没记错，苹果的电脑不兼容这种设备，所以用不了

**Comment by ControlNet** [comment]
这里的原因是指这个checkpoint文件保存的权重是映射到cuda设备上的，所以会直接加载到GPU上，而MacOS没有GPU，所以不能加载模型。

按照上面的提示，把`torch.load`设置`map_location="cpu"`就可以先把模型加载到CPU上，然后再在CPU上运行即可。

**Comment by Starry-OvO** [comment]
纯cpu带不动吧，torch对苹果的适配这么好吗

**Comment by ControlNet** [comment]
用CPU只是一个resnet50应该问题不大，而且如果折腾一下环境的话，用gpu加速也是可以的，`device = Device("mps")`

**Comment by WdBly** [comment]
> 这里的原因是指这个checkpoint文件保存的权重是映射到cuda设备上的，所以会直接加载到GPU上，而MacOS没有GPU，所以不能加载模型。
> 
> 按照上面的提示，把`torch.load`设置`map_location="cpu"`就可以先把模型加载到CPU上，然后再在CPU上运行即可。

model = model.to(device=device)

**Comment by Starry-OvO** [comment]
首先我没有能运行macOS的设备，只能云听诊；其次你这个“还是会报错”又是报的什么错呢？

**Comment by WdBly** [comment]
model.load_state_dict(torch.load(str(model_path), map_location ='cpu'))
        model = model.to(device=torch.device('cpu'))
        ....
        img_ts = img_ts.to(device=torch.device('cpu'))
        
        已解决，mac需要修改这三行代码
