### ISSUE TITLE
batch_count为0

### ISSUE THREAD

**Issue by 1176642936** [Starry-OvO/rotate-captcha-crack#2]
batch_count为0是什么原因？  我这边图集是png的匹配也修改了

**Comment by Starry-OvO** [comment]
你不会只改了`dataset.py`里的那个`masks='*.jpg'`吧，`prepare.py`里保存的也是jpg

**Comment by 1176642936** [comment]
都修改了的



***@***.***
 
发件人： Starry-OvO
发送时间： 2022-07-07 21:07
收件人： Starry-OvO/Rotate-Captcha-Crack
抄送： Yqiu32; Author
主题： Re: [Starry-OvO/Rotate-Captcha-Crack] batch_count为0 (Issue #2)
你不会只改了dataset.py里的那个masks='*.jpg'吧，prepare.py里保存的也是jpg
