### ISSUE TITLE
报错float division by zero

### ISSUE THREAD

**Issue by cmdcam** [Starry-OvO/rotate-captcha-crack#21]
新手不太会用，在google的colab上跑的，报错了。
`<2023-08-19 04:13:27.135> [DEBUG] Epoch#0. Training process.
 15% 19/128 [00:37<03:34,  1.97s/it]
<2023-08-19 04:14:04.551> [DEBUG] Epoch#0. Validating process.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/rotate-captcha-crack-master/train_RotNetR.py", line 71, in <module>
    trainer.train()
  File "/content/drive/MyDrive/rotate-captcha-crack-master/rotate_captcha_crack/trainer.py", line 207, in train
    val_loss = total_val_loss / eval_batch_count
ZeroDivisionError: float division by zero`
是哪里设置错了吗？有1千多张图片。
![image](https://github.com/Starry-OvO/rotate-captcha-crack/assets/128442507/f811b416-449f-45b5-9965-c1940666a858)

**Comment by Starry-OvO** [comment]
是太少了，把验证集的比例调大一点能解决错误，但这个数据量还是很难得到比较好的效果

**Comment by cmdcam** [comment]
如果每张图片搞360张呢，每张图片每个角度弄一张，会有问题吗？可以这样弄吗？

**Comment by Starry-OvO** [comment]
肯定没用，纹理模式就那么多，很容易过拟合的

**Comment by cmdcam** [comment]
底图一样，底图角度不一样，但每张图片上的文字不一样，这样有效果吗？bd的图片有点少，就那么多了。

**Comment by Starry-OvO** [comment]
效果会很差，因为这个文字只是个干扰项没什么规律的。一般抓下来的都是没有文字的啊，除非你用Playwright之类的框架导致图片链接被二次使用。

**Comment by cmdcam** [comment]
谢谢解答！
有什么好方法推荐吗？主要是过bd。手上有人家训练好的，但是比较老了，效果不咋地，不太准。市场上也有专门过验证的，不知道怎么弄的。。

**Comment by Starry-OvO** [comment]
拿风景图或者ai生成的风景图（不知道有没有这种数据集）去训练啊，比如Google Landmark

**Comment by cmdcam** [comment]
谢谢，bd现在验证好像用ai图片了，我去找找有没有这个数据。

**Comment by cmdcam** [comment]
大佬，被训练的图片绝大部分都是旋转了的，需要手动摆正吗？
还有大概最少要多少张图片才有个比较好的效果啊？

**Comment by Starry-OvO** [comment]
需要手动摆正。我用的数据集是1万张

**Comment by cmdcam** [comment]
大佬，有BD验证码源码没，我这边已经有图片角度和op=1了，但好像还差点意思，后续不知道怎么弄了，有这方面的源码没，不白嫖！需要JS逆向的，有的话，留个联系方式哈。

**Comment by Starry-OvO** [comment]
我不做js逆向的，那个有点复杂，太花时间了

**Comment by zhaotaogit** [comment]
> 大佬，有BD验证码源码没，我金字塔已经有图片角度和op=1了，但想要还差点意思，后续不知道怎么弄了，有这方面的源码没，不白嫖！需要JS逆向的，有的话，留个联系方式哈。

我有哦，+QQ 1787417712
