### ISSUE TITLE
RuntimeError (CUDA)

### ISSUE THREAD

**Issue by SVJA7IK** [Starry-OvO/rotate-captcha-crack#27]
I'm running code on a version of Python 3.10 via server.py. For some reason I get an error : **RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to ma
p your storages to the CPU.**

**Comment by Starry-OvO** [comment]
If you already have a CUDA device, maybe you need to install PyTorch with CUDA runtime, see [this tutorial](https://telin.ugent.be/telin-docs/windows/pytorch/).
