### ISSUE TITLE
about the work

### ISSUE THREAD

**Issue by young525** [Starry-OvO/rotate-captcha-crack#28]
Do you have a paper with the work?

**Comment by Starry-OvO** [comment]
This work is not novel enough so I may not draw a paper. But here is another paper inspired me about how to deal with the circular symmetric features: [Arbitrary-Oriented Object Detection with Circular Smooth Label (ECCV 2020)](https://www.researchgate.net/profile/Xue-Yang-69/publication/343636147_Arbitrary-Oriented_Object_Detection_with_Circular_Smooth_Label/links/5f46456b458515b7295797fd/Arbitrary-Oriented-Object-Detection-with-Circular-Smooth-Label.pdf). I'll soon apply this concept into this project.

**Comment by young525** [comment]
Thanks,Bro,god bless you!
