### ISSUE TITLE
class ImgWithLabel[TLabel] : python 3.8 不支持此语法

### ISSUE THREAD

**Issue by yintian710** [Starry-OvO/rotate-captcha-crack#29]
Python 依赖版本错误?
![image](https://github.com/Starry-OvO/rotate-captcha-crack/assets/59188000/12b1daa0-a1c5-4bf2-96e0-5721980bc9f1)
![image](https://github.com/Starry-OvO/rotate-captcha-crack/assets/59188000/b2db00d0-427a-4967-a7cb-58412524e4e0)

**Comment by Starry-OvO** [comment]
emmm确实忘了改了，这是3.10（好像是）才有的泛型语法，晚上回去改

**Comment by Starry-OvO** [comment]
改了一下，现在应该可以了

**Comment by py-syy** [comment]
大佬这是啥问题啊！！！，求解
![image](https://github.com/Starry-OvO/rotate-captcha-crack/assets/67097666/52b1d010-3e2f-4c5b-a933-96646305a936)

**Comment by Starry-OvO** [comment]
Solved in #30
