### ISSUE TITLE
    def __call__(self, data: ImgWithLabel[float]) -> ImgWithLabel[Tensor]: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by py-syy** [Starry-OvO/rotate-captcha-crack#30]
大佬这是啥问题啊！！！，求解

![image](https://github.com/Starry-OvO/rotate-captcha-crack/assets/67097666/961ce77a-3e40-436b-8ba1-3d76a5574065)

**Comment by Starry-OvO** [comment]
看看这个commit https://github.com/Starry-OvO/rotate-captcha-crack/commit/935dd56a322ea14aa5124759ae991abd4ca967a7 能不能解决问题，我在外边没gpu，没法debug只能靠脑测

**Comment by py-syy** [comment]
报找不到模型路径，不是放到根目录吗
![image](https://github.com/Starry-OvO/rotate-captcha-crack/assets/67097666/7df2cba3-55c6-45b1-8240-475ad0371de6)

**Comment by Starry-OvO** [comment]
https://github.com/Starry-OvO/rotate-captcha-crack/blob/master/README_zh-cn.md#下载预训练模型
