### ISSUE TITLE
请教训练结束后，执行 test_captcha出问题

### ISSUE THREAD

**Issue by RobotZQ** [Starry-OvO/rotate-captcha-crack#32]
device 是mps 进行自己的图片训练后，执行test_captcha.py出现这个
Use model: models/RotNetR/240709_09_15_14_002/best.pth
[1]    12915 segmentation fault  Python test_captcha.py
是 device 的问题吗？

**Comment by Starry-OvO** [comment]
说实话我不太清楚是什么问题，你要不断点调一下看是哪一行报的段错误

**Comment by RobotZQ** [comment]
> 说实话我不太清楚是什么问题，你要不断点调一下看是哪一行报的段错误
torch._C._nn._upsample_bilinear2d_aa(input, output_size, align_corners, scale_factors)
torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
这里它会直接退出程序

**Comment by Starry-OvO** [comment]
我晚上回去看看，这bug有点神奇

**Comment by RobotZQ** [comment]
> 我晚上回去看看，这bug有点神奇
多谢，不知道是不是因为我是 M1 芯片不兼容

**Comment by Starry-OvO** [comment]
你现在用的是哪个版本的numpy，我还没看numpy2.0更新的内容
