### ISSUE TITLE
请问大佬数据集得格式

### ISSUE THREAD

**Issue by xiangbei1997** [Starry-OvO/rotate-captcha-crack#4]
需要标注角度吗?

**Comment by Starry-OvO** [comment]
不用，角度标签自动生成
不过感觉全随机的效果不如RotNet的四种角度取值

**Comment by xiangbei1997** [comment]
大佬建议添加个图片检测是否能打开, 再运行prepare.py 的时候会退出

**Comment by Starry-OvO** [comment]
这个仓库我估计一时半会不会动了，这个课题深挖一下可以发篇sci三-四区，剪枝量化的优化空间也很大，估计得等明年有空了再做这些吧

**Comment by xiangbei1997** [comment]
我用了5000张图片,训练了650个批次,效果很差,虽然eval_loss已经很低了,但是真实图片识别效果很差,图片来源是百度的验证码图片,像这样的大佬我需要改什么吗,还是哪里搞错了.
![image](https://user-images.githubusercontent.com/35731898/195010736-9eda2adf-e6fb-45c4-9584-9dca52ded969.png)

![image](https://user-images.githubusercontent.com/35731898/195010578-2c36b6d1-f4bc-4ab3-9db4-195d0e304c0b.png)
