### ISSUE TITLE
训练后输出里没有前 18 个 Epoch

### ISSUE THREAD

**Issue by BangKk** [Starry-OvO/rotate-captcha-crack#5]
如图：
<img width="320" alt="image" src="https://user-images.githubusercontent.com/13979818/213059367-8511007f-1210-43d0-a648-d5b03749bb02.png">
但看控制台输出了前 18 个 Epoch 的日志，请问是啥原因啊？

**Comment by BangKk** [comment]
看源码好像以上是没问题的？
<img width="748" alt="image" src="https://user-images.githubusercontent.com/13979818/213060050-0cf79af0-86fa-4d35-9a5c-0de53af64428.png">

**Comment by BangKk** [comment]
但我测试发现角度偏差还是有点大，请问你训练用了 [Landscape-Dataset](https://github.com/koishi70/Landscape-Dataset) 多少个压缩包的文件？

**Comment by Starry-OvO** [comment]
数据集我是全用了
前一半的epoches都是不输出的，不然输出的太多了，如果需要输出的话可以把那个if删掉

**Comment by BangKk** [comment]
感谢回复。我测试了这张图片，但效果不是很好，是因为图片中黑色的部分吗？如何让它输出更准确，你有什么建议吗
![4](https://user-images.githubusercontent.com/13979818/213080886-2e67142c-d164-42f4-813a-2d2fa02c5b03.jpg)
<img width="640" alt="image" src="https://user-images.githubusercontent.com/13979818/213080964-18b37acc-ad6a-438e-bcbd-2b73831e8d71.png">

**Comment by BangKk** [comment]
我试了几张图片，偏差的度数是固定的

**Comment by Starry-OvO** [comment]
既然数据集的边缘是纯白的，那你的输入最好也是纯白的，那样效果才会比较正常

**Comment by BangKk** [comment]
> 既然数据集的边缘是纯白的，那你的输入最好也是纯白的，那样效果才会比较正常

嗯嗯，感谢你的回复~
