### ISSUE TITLE
模型性能提升到13°

### ISSUE THREAD

**Issue by ControlNet** [Starry-OvO/rotate-captcha-crack#6]
发现原来的模型有些欠拟合，稍微改了一点参数在不太增加性能开销的同时提高了准确度。

如果作者觉得这个改进有帮助的话，会提交一个pr。

做的修改有
- 全连接层增加到2层
- 降低LR到4e-4
- 设定epoch = 3000，在epoch = 190的时候达到最优结果
- batch_size = 128

### 定量比较

|     |  Error |  MAC  | PARAMS |
|:---:|:------:|:-----:|:------:|
| OLD | 19.98° | 1.63G |  8.28M |
| NEW | 13.09° | 1.63G |  9.11M |

### 定性比较

![image](https://user-images.githubusercontent.com/12800094/213630340-b9300a8a-0965-4fdc-b6c8-cfd0681310b9.png)

### 训练过程 eval_loss.png

![eval_loss](https://user-images.githubusercontent.com/12800094/213634710-826cbc98-3d91-4c79-93ab-ac3c5aca2846.png)

**Comment by Starry-OvO** [comment]
我觉得可以

**Comment by Starry-OvO** [comment]
对了，如果要pr的话就不用提交新模型了，老模型也可以删掉，git不适合存这种大文件，还是网盘好用

**Comment by ControlNet** [comment]
其实对于这种小模型，感觉可以通过github release来存

**Comment by Starry-OvO** [comment]
也可以

**Comment by langyo** [comment]
> > 对了，如果要pr的话就不用提交新模型了，老模型也可以删掉，git不适合存这种大文件，还是网盘好用
> 
> 小心52pojie那群广告黑灰产发issue问您为啥不能开箱即用

这不是正好嘛，让他们爬去

**Comment by n0099** [comment]
> > > 对了，如果要pr的话就不用提交新模型了，老模型也可以删掉，git不适合存这种大文件，还是网盘好用
> > 
> > 
> > 小心52pojie那群广告黑灰产发issue问您为啥不能开箱即用
> 
> 这不是正好嘛，让他们爬去

与此同时 https://github.com/HuanCheng65/TiebaLite/issues/145#issuecomment-1376899792
https://www.52pojie.cn/thread-1648818-1-1.html
> 没有api：starry神 @Starry-OvO 已于2022年6月发威逆向出了在im.tieba.baidu.com:8000的ws服务隐藏之下的protobuf
而这个ws endpoint早在17年就业已被贴吧工具人们挖了出来 [bbs.tiebazs.com/593-1-1.html](https://bbs.tiebazs.com/593-1-1.html) 但当时他们还不知道这是干嘛的
